using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ContosoCrafts.WebSite.Models
{
    /// <summary>
    /// Created a class for ProductModel
    /// </summary>
    public class ProductModel
    {   // Store the ID of Profession auto generated by guid in jsonfileproductservice.
        public string Id { get; set; }

        // Store the Name of Maker
        public string Maker { get; set; }

        // Store the Email Id of Maker
        public string MakerEmail { get; set; }

        // Store the url, Image of Maker
        [JsonPropertyName("img")]
        public string Image { get; set; }
        
        //This is used to get url and set url value
        public string Url { get; set; }

        // Store the title of Profession
        public string Title { get; set; }

        // Store the Description of Profession
        public string Description { get; set; }

        // Store the Ratings of Maker 
        public int[] Ratings { get; set; }
        
        /// <summary>
        /// To improve program's readability with a group of constants
        /// </summary>
        public ProductTypeEnum ProductType { get; set; } = ProductTypeEnum.Undefined;

        // Store the quantity of Makers available
        public string Quantity { get; set; }

        // Store the Price charged by Maker
        public decimal Price { get; set; }
        
        // Store the Comments entered by the users on this Profession
        public List<CommentModel> CommentList { get; set; } = new List<CommentModel>();
        public override string ToString() => JsonSerializer.Serialize<ProductModel>(this);
    }
}